source 'http://10.10.5.215:7880/iosteam/tcspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'TCCloudTalking_Example' do
  pod 'TCCloudTalking', :path => '../'
  
  target 'TCCloudTalking_Tests' do
    inherit! :search_paths
    
    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
