source 'http://10.10.5.215:7880/iosteam/tcspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'TCCloudTalking_Example' do
  pod 'TCCloudTalking', :path => '../'
  
  target 'TCCloudTalking_Tests' do
    inherit! :search_paths
    
    pod 'FBSnapshotTestCase'
  end
end
